GET http://localhost:8080/ads/1/comments
Content-Type: application/json
Authorization: Basic user@gmail.com password

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user@gmail.com",
  "password": "12345678"
}

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "user@gmail.com",
  "password": "12345678",
  "firstName": "Nikita",
  "lastName": "Vdovin",
  "phone": " +79222090566",
  "role": "USER"
}

###
GET http://localhost:8080/ads/me
Content-Type: application/json
Authorization: Basic user@gmail.com password

###
GET http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic user@gmail.com password

###
PATCH http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic user@gmail.com password

{
  "phone": "+79001234568",
  "lastName": "Vovin",
  "firstName": "Nikit"
}

###
GET http://localhost:8080/ads
Content-Type: application/json
Authorization: Basic user@gmail.com password

###
POST http://localhost:8080/users/set_password
Content-Type: application/json
Authorization: Basic user@gmail.com password

{
  "newPassword": "87654321",
  "currentPassword": "12345678"
}

###
POST http://localhost:8080/ads
Content-Type: application/json
Authorization: Basic user@gmail.com password

{
  "price": 5000,
  "description": "Крутая футболка",
  "title": "Футболка"
}